# Generated by Django 6.0 on 2026-01-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="last_triggered",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reminder",
            name="repeat_weekly",
            field=models.BooleanField(default=False),
        ),
    ]
