# Generated by Django 6.0 on 2026-01-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_reminder_last_triggered_reminder_repeat_weekly"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reminder",
            name="last_triggered",
        ),
        migrations.AddField(
            model_name="reminder",
            name="is_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="is_completed",
            field=models.BooleanField(default=True),
        ),
    ]
